version: "3.3"
services:
  aspen-dev-box:
    image: registry.gitlab.com/aspen-discovery/aspen-dev-box-image/aspen-dev-box:main
    volumes:
      - "$ASPEN_CLONE:/usr/local/aspen-discovery"
      - "$ASPEN_DOCKER/site/:/usr/local/aspen-discovery/sites/test.localhostaspen"
      - "$ASPEN_DOCKER/etc/apache2/sites-enabled:/etc/apache2/sites-enabled"
      - "$ASPEN_DOCKER/site/conf/crontab_settings.txt:/etc/cron.d/cron"
      - "$ASPEN_DOCKER/aliases:/root/.bashrc"
    ports:
      - "8084:8080"
      - "8083:80"
    container_name: containeraspen
    networks:
      - koha_kohanet
    tty: true
    platform: linux/amd64

  aspendb:
    container_name: aspen-db
    environment:
      - MYSQL_ROOT_PASSWORD=aspen
      - MYSQL_DATABASE:aspen
      - MYSQL_USER:aspensuper
      - MYSQL_PASSWORD:aspensuper
      - MYSQL_TCP_PORT:7000
    image: "mariadb:10.5"
    volumes:
      - $ASPEN_DOCKER/setup.sql:/docker-entrypoint-initdb.d/init-script.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-paspen", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - koha_kohanet
    platform: linux/amd64

networks:
  koha_kohanet:
    name: koha_kohanet
    external: true
