services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8085:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=aspen-db
      - PMA_USER=aspensuper
      - PMA_PASSWORD=aspensuper
    networks:
      - koha_kohanet

